server {
	listen 2222;
	server_name localhost;
	root www/beboccas

	#10GB
	client_max_body_size 10000000000; 

	location / {
		method GET;
		autoindex off;
		index index.html;
	}

	location /links {
		root www/littlelink;
		method GET;
		autoindex on;
		index index.html;
	}

	location /cgi-bin {
		root www/cgi-bin
		method GET POST;
		cgi_path /usr/bin/bash;
	}
}