
# note syl If the port is empty or not given, port 80 is assumed

server {
	listen 2224;
	server_name localhost;
	error_page 404 errors/404.html;
	error_page 400 errors/400.html;
	error_page 405 errors/405.html;
	error_page 500 502 errors/50x.html;

	root www/origameee
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
	location /cgi-bin {
		root www/origameee
		method GET POST;
		cgi_path /usr/bin/python3;
	}
}

server {
	listen 2223;
	server_name 127.0.0.1;
	error_page 404 errors/404.html;
	error_page 400 errors/400.html;
	error_page 405 errors/405.html;

	root www/beboccas
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
	location /cgi-bin {
		root www/cgi-bin
		method GET POST;
		cgi_path /usr/bin/bash;
	}
}

server {
	listen 2222;
	server_name c2r3s4.42lausanne.ch; // type hostname dans terminal
	error_page 404 errors/404.html;
	error_page 400 errors/400.html;
	error_page 405 errors/405.html;

	root www/beboccas
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
	location /cgi-bin {
		root www/origameee
		method GET POST;
		cgi_path /usr/bin/python3;
	}
}



