server {
	listen 2224;
	server_name localhost;
	error_page 404 errors/404.html;
	error_page 400 errors/400.html;
	error_page 405 errors/405.html;
	error_page 500 502 errors/50x.html;

	root www/origameee
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
}

server {
	listen 8080;
	server_name localhost;
	root www/beboccas
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
	location /cgi-bin {
		root www/cgi-bin
		method GET POST;
		cgi_path /usr/bin/bash;
	}
}

server {
	listen 8888;
	server_name localhost;
	error_page 404 errors/404.html;
	error_page 400 errors/400.html;
	error_page 405 errors/405.html;

	root www/littlelink
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
}



