server {
    listen 8080;
    server_name localhost;
    
    root www;
    client_max_body_size 10000000000;
    
    location / {
        methods GET;
        autoindex on;
        index index.html;
    }
    
    location /uploads {
        methods POST DELETE;
        upload_path www/uploads;
    }
}