
# note syl If the port is empty or not given, port 80 is assumed

server {
	listen 2224;
	server_name localhost;

	root www/origameee
	client_max_body_size 100000;

	location / {
		method GET;
		autoindex off;
		index index.html;
	}
	location /cgi-bin {
		root www/origameee
		method GET POST;
		cgi_path /usr/bin/python3;
	}
}
