server {
	listen 2222;
	server_name localhost;
	root www/beboccas/testpage
	client_max_body_size 10000000000; 

	location / {
		method GET;
		autoindex off;
		index index.html;
	}

	location /links {
		root www/littlelink;
		method GET;
		autoindex on;
		index index.html;
	}

	location /beboccas {
		root www/beboccas;
		method GET;
		autoindex on;
		index index.html;
	}

	location /origameee {
		root www/origameee;
		method GET;
		autoindex on;
		index index.html;
	}

	location /cgi-bin {
		root www/cgi-bin
		method GET POST;
		cgi_path /usr/bin/bash;
	}
}