server {
    listen 8080;
    server_name localhost;

    root www/origameee;
    index index.html;

    client_max_body_size 10000000;

    error_page 400 www/errors/400.html;
    error_page 403 www/errors/403.html;
    error_page 404 www/errors/404.html;
    error_page 405 www/errors/405.html;
    error_page 500 502 503 504 www/errors/50x.html;

    location / {
        methods GET HEAD;
        autoindex off;
    }

    location /docs/ {
        methods GET HEAD;
        autoindex on;
    }

    location /cgi-bin/ {
        methods GET POST DELETE;
        cgi_path www/cgi-bin;
    }
}
