server {
    listen 8080;
    server_name localhost;

    # Point to the SAME fixtures directory nginx uses
    root tester_v2/fixtures/html;
    client_max_body_size 10000000;

    # Error pages from fixtures
    error_page 400 tester_v2/fixtures/errors/400.html;
    error_page 403 tester_v2/fixtures/errors/403.html;
    error_page 404 tester_v2/fixtures/errors/404.html;
    error_page 405 tester_v2/fixtures/errors/405.html;

    # Main location - only GET and HEAD
    location / {
        methods GET HEAD;
        autoindex off;
		index tiny.html;
    }

    # CGI location
    location /cgi-bin/ {
        methods GET POST;
        root tester_v2/fixtures/cgi;
    }
}
