#!/bin/bash

echo "Content-Type: text/html; charset=UTF-8"
echo ""
echo "<html>"
echo "<head>"
echo "<meta charset='UTF-8'>"
echo "<title>CGI Test</title>"
echo "</head>"
echo "<body>"
echo "<h1>Hello from CGI!</h1>"
echo "<p>Request Method: $REQUEST_METHOD</p>"
echo "<p>Query String: $QUERY_STRING</p>"
echo "<p>Script Name: $SCRIPT_NAME</p>"
echo "<p>HTTP Host: $HTTP_HOST</p>"
echo "</body>"
echo "</html>"
